#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

IMAGE_NAME="mtlynch/gae-tester"
CONTAINER_NAME="appengine-seed"

docker version

docker rm -f "$CONTAINER_NAME" || true

docker run \
  --tty \
  --detach \
  --volume "${PWD}:/app" \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"

docker exec "$CONTAINER_NAME" pip install -r dev_requirements.txt
docker exec "$CONTAINER_NAME" ./build
